# sample netlify.toml
[build]
  command = "npm run build"
  publish = "public"

# note: each of these fields are OPTIONAL, with an exception that when you're specifying "command" and "port", you must specify framework = "#custom"
[dev]
  framework = "#custom"
  command = "run-p watch micro serve"
  # targetPort = 3000 # The port for your application server, framework or site generator
  targetPort = 8888 # The port that the netlify dev will be accessible on
  publish = "public" # The path to your static content folder
  # jwtRolePath = "app_metadata.authorization.roles" # Object path we should look for role values for JWT based redirects
  autoLaunch = true # a Boolean value that determines if Netlify Dev launches the local server address in your browser

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200